Repository elastic/beats-tester, pull requests merged in 2019-01, with the labels that each got.

#105 Check that Beat ships with the right binary
  roles/test-beat/tasks/common/assert.yml
Labels: enhancement, review

#106 Fix Linux package install and uninstall
  roles/common/defaults/main.yml
  roles/test-install/tasks/main.yml
Labels: bug, review

#107 Auditbeat System module: Change metricsets to datasets
  roles/test-beat/templates/auditbeat.yml.j2
Labels: review
